version: '2.1'
services:
  master:
    build: .
    environment:
      - SPARK_MASTER_HOST=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=5055
    ports:
      - 7077:7077
      - 5055:5055
    entrypoint: [ "./entrypoint.sh", "master" ]
  
  worker:
    build: .
    environment:
      - SPARK_MASTER_HOST=master
      - SPARK_MASTER_PORT=7077
    depends_on:
      - master
    entrypoint: [ "./entrypoint.sh", "worker"]
