name: superset
channels:
- defaults
dependencies:
- python=3.6
- pip
- pip:
  - superset
  - pandas==0.23.4
  - pyhive==0.6.1
  - cryptography==2.3.1
  - psycopg2-binary==2.7.7
  - mysqlclient==1.4.1
  - gevent==1.4.0
